name: CI

on:
  release:
    types: [created]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.3
        env:
          GITHUB_TOKEN: ${{ github.token }}
          
      - name: Set version in toc
        run: |
          sed -i 's/{version}/${{ steps.get_release.outputs.tag_name }}/g' ameno.toc

      - name: Set version in main.lua
        run: |
          sed -i -r 's/amenoversion=\"[0-9]+.[0-9]+.[0-9]/amenoversion=\"${{ steps.get_release.outputs.tag_name }}/g' main.lua

      # Copy desired files in new folder and create archive
      - name: Create Archive
        run: |
          mkdir ameno
          rsync -a --exclude=/ameno --exclude=.gitignore --exclude=README.md --exclude=LICENSE --exclude=/.github ./ ./ameno
          zip -r ameno-${{ steps.get_release.outputs.tag_name }}.zip ./ameno

      # Add archive to release
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./ameno-${{ steps.get_release.outputs.tag_name }}.zip
          asset_name: ameno-${{ steps.get_release.outputs.tag_name }}.zip
          asset_content_type: application/zip
